---
title: "Analyse Piscine - Eau - Boiler"
author: "jcb"
date: "2026-05-15"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r setup, include=FALSE, eval=TRUE,results='hide',message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html")
# delete all objects and garbage collection	
rm(list = ls(all.names = TRUE))
gc()
# pour mettre les html dans un dossier dédié
#ezknit( file = "./rmd-Eau_Elec_2021-11-19.Rmd",out_dir = "reports", fig_dir = "myfigs")
```
Nom de ce Script R: `r get(env = parent.frame(n = 8), 'input')`<br>
<br>
`r paste0("Version : ",Sys.Date())`
<br>
```{r jcb Librairies, include=FALSE, eval=TRUE,results='hide',message=FALSE,warning=FALSE}
jcb_Library <-function(pkg){
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library (pkg, character.only = TRUE)
}
install_if_missing <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
}

jcb_Library("rstudioapi")
jcb_Library("ggplot2")
jcb_Library("dplyr")
jcb_Library("lubridate")
jcb_Library("zoo")

#install_if_missing("RSQLite")
#install_if_missing("stringr")
```
```{r jcb Script Header - Global Data et Paramètres, include=FALSE, eval=TRUE,results='hide',message=FALSE,warning=FALSE}
CWD <- getwd() # Ger Current Dir
PrjDir <- usefun::get_parent_dir(CWD) # Get Dir du projet pycharm c'est la racine du projet
ScriptName <- basename(rstudioapi::getSourceEditorContext()$path)
ScriptDirName <- dirname(rstudioapi::getSourceEditorContext()$path)
AllCSVFileName="/Log_Energie.csv"
AllEnergiePath <- paste(PrjDir,AllCSVFileName,sep="")

```
`r paste0("ScriptName: ",ScriptName,"\n")`
`r paste0("ScriptDirName: ",ScriptDirName,"\n")`
`r paste0("AllEnergiePath: ",AllEnergiePath,"\n")`
<br>

```{r Get and Prepare Data, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}
AllEnergie <- read.csv(AllEnergiePath, header = TRUE,      # première ligne = noms de colonnes
                 sep = ",",          # séparateur ("," par défaut)
                 stringsAsFactors = FALSE)

#AllEnergie <- AllEnergie %>% select(-c(X))
AllEnergie$TimeStamp <-dmy_hm(paste(AllEnergie$Date, AllEnergie$Heure))

```
```{r Fonctions, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}

ConsoAnnuelle <- function(Test){
  TestM1 <- lag(Test,1) 
  TestM1 <- tail(TestM1,nrow(TestM1)-1)
  Test <- tail(Test,nrow(Test)-1)
  Test$DeltaConso <-Test$Index - TestM1$Index 
  Test$DeltaTS <-Test$TimeStamp - TestM1$TimeStamp
  Test <- Test %>% mutate(Annuel = DeltaConso*365.25/as.numeric(DeltaTS))
  Test <- Test %>% select(c(TimeStamp,Energie,Annuel))
  return(Test)
}
# A ce stade le code est général
```
```{r Function Plot Energie, echo=FALSE,eval=TRUE,message=FALSE,warning=FALSE}


PlotEnergie <- function ( pEnergie){
  EnergieAnnualisee <- ConsoAnnuelle(pEnergie)
  gg <- ggplot(EnergieAnnualisee, aes(x = TimeStamp, y = Annuel,colour = "Locale Normalisée")) +
  geom_line() +
  #geom_smooth(se = FALSE, method = "loess") +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = paste(ParaEnergie," - Valeur Instantanée et Moyenne Mobile"))
  #(gg)
  EnergieAnnualisee <- EnergieAnnualisee %>% mutate(Date = as.Date(TimeStamp) )
  EnergieAnnualisee <- EnergieAnnualisee %>% mutate( Mois = floor_date(TimeStamp, unit = "month"))
  Last_Date <- EnergieAnnualisee[nrow(EnergieAnnualisee),]$Mois
  Last_Date_M2A <- Last_Date %m-% years(1)
  Index_de_ANM1 <- which(EnergieAnnualisee$Mois == Last_Date_M2A)
  MeanRange <- ifelse (is.na(Index_de_ANM1), as.integer(nrow(EnergieAnnualisee)/2),as.integer((nrow(EnergieAnnualisee) - Index_de_ANM1))) 
  EnergieAnnualisee <- EnergieAnnualisee %>% mutate(GlobMM =  rollmean(Annuel, k = MeanRange, fill = NA, align = "right")) 
  gg <- gg +
  geom_line(data = EnergieAnnualisee, aes(x = TimeStamp, y = GlobMM,colour = "Moyenne Mobile")) 
    #geom_line(data = ConsoGlob, aes(x = TimeStamp, y = JourMM, color = "Jour Mobile")) +
    #geom_line(data = ConsoGlob, aes(x = TimeStamp, y = NuitMM, color = "Nuit Mobile")) +
    #labs(title = "Moyennes Mobiles") +
    #scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m-%d") +
    #theme(axis.text.x = element_text(angle = 45, hjust = 1))
  return(gg)
}
ParaEnergie <- "Pisc" # Exercice avec Eau
Piscine <- AllEnergie %>% filter (Energie == ParaEnergie) 
# on calcule ConsoAnnuelle
PlotPiscine <- PlotEnergie(Piscine)
(PlotPiscine)
ParaEnergie <- "Eau" # Exercice avec Eau
Eau <- AllEnergie %>% filter (Energie == ParaEnergie) 
PlotEau <- PlotEnergie(Eau)
(PlotEau)
ParaEnergie <- "Boiler" # Exercice avec Eau
Boiler <- AllEnergie %>% filter (Energie == ParaEnergie) 
PlotBoiler <- PlotEnergie(Boiler)
(PlotBoiler)






```

